### ISSUE TITLE
Some js errors in posit1.js

### ISSUE THREAD

**Issue by jeromeetienne** [jcmellado/js-aruco#6]
Hi 

Im playing with js-aruco, it is a lot of fun 

Nevertheless i often get an js exception as error1 and error2 being undefined in line 118. it seems to occurs randomly when i move the marker in front of the camera. it occurs even with your debug.html. 
i know this is old code, but it gained popularity with the gogglepaper.com stuff :)

Any hint on how to fix it ?

from https://github.com/jcmellado/js-aruco/blob/master/src/posit1.js#L118

```
  return error1.euclidean < error2.euclidean?
    new POS.Pose(error1.pixels, rotation1, translation1, error2.pixels, rotation2, translation2):
    new POS.Pose(error2.pixels, rotation2, translation2, error1.pixels, rotation1, translation1);
};
```

**Comment by jcmellado** [comment]
Ok, it took me a lot of time, but here is:
`Uncaught TypeError: Cannot read property 'euclidean' of undefined - posit1.js:119`

Looking at the code, I think that the issue happens when the iterative POSIT algorithm (used to estimate the pose of the camera) converges before the first iteration:

```  
  var error;
  ...
  converged = (0.0 === error1.pixels) || (imageDifference < 0.01);
  while( iteration ++ < 100 && !converged ){
    ...
    // bla, bla, ... error = some value (never reached)
    ...
  }
  return error; // <= undefined
```

I'll try to fix it.

In the meantime, you should try with the second POSIT algorithm (posit2.js) already included with the library. Just change this import: `<script type="text/javascript" src="posit1.js">` to `..."posit2.js">`
